[build]
  base = "."
  command = "npx tsc --noEmit && npx vite build"
  publish = "dist/public"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"